server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

logging:
  file:
    name: logs/api-gateway.log
    path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    io.github.mrlevi1112: DEBUG

services:
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8002}
    name: auth-service
  report:
    url: ${REPORT_SERVICE_URL:http://localhost:8003}
    name: report-service